### ISSUE TITLE
[Bug] Run epoch over multiple minibatches

### ISSUE THREAD

**Issue by RobertTLange** [bmazoure/ppo_jax#1]
Hi @bmazoure,

Thank you for making this open source! Great minimal codebase. Not sure if I am missing something, but it appears as if an epoch only processes a single mini-batch, since you return after the first iteration within the loop.

https://github.com/bmazoure/ppo_jax/blob/504491e938e50466f025a70cddd7706dfedb072e/algo.py#L164-L195

I can open a PR if you would like me to.

P.S.: I also believe you do not need the `static_argnums` since the shapes do not depend on `clip_eps`.

**Comment by bmazoure** [comment]
Ah yes, good catch! I locally don't have this issue, so must've been somehow a tabulation misalignment with the return statement. I'll fix it asap.

**Comment by bmazoure** [comment]
Closing because the issue was fixed.
